### ISSUE TITLE
please update go version to 1.11 or higher

### ISSUE THREAD

**Issue by branchmaster** [hi20160616/youtube_web#1]
hi hi20160616 , 
I'm trying to deploy on heroku but fail on package ,see fail deploy full log below :
-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/go
-----> Go app detected
-----> Fetching jq... done
-----> Fetching stdlib.sh.v8... done
-----> 
       Detected go modules via go.mod
-----> 
       Detected Module Name: github.com/hi20160616/youtube_web
-----> 
 !!    The go.mod file for this project does not specify a Go version
 !!    
 !!    Defaulting to go1.12.17
 !!    
 !!    For more details see: https://devcenter.heroku.com/articles/go-apps-with-modules#build-configuration
 !!    
-----> New Go Version, clearing old cache
-----> Installing go1.12.17
-----> Fetching go1.12.17.linux-amd64.tar.gz... done
-----> Determining packages to install
       
       Detected the following main packages to install:
       		github.com/hi20160616/youtube_web/cmd/server
       
-----> Running: go install -v -tags heroku github.com/hi20160616/youtube_web/cmd/server 
google.golang.org/protobuf/internal/flags
github.com/pkg/errors
google.golang.org/api/googleapi/transport
google.golang.org/api/internal/third_party/uritemplates
golang.org/x/net/internal/timeseries
google.golang.org/api/googleapi
golang.org/x/net/trace
google.golang.org/grpc/backoff
google.golang.org/grpc/internal/grpclog
google.golang.org/grpc/grpclog
google.golang.org/grpc/connectivity
google.golang.org/protobuf/internal/detrand
google.golang.org/protobuf/internal/pragma
google.golang.org/protobuf/internal/set
google.golang.org/protobuf/internal/errors
google.golang.org/protobuf/internal/version
google.golang.org/grpc/attributes
google.golang.org/protobuf/encoding/protowire
google.golang.org/grpc/serviceconfig
google.golang.org/grpc/internal
google.golang.org/grpc/internal/credentials
google.golang.org/protobuf/reflect/protoreflect
google.golang.org/grpc/metadata
google.golang.org/grpc/internal/grpcrand
google.golang.org/grpc/codes
google.golang.org/grpc/encoding
google.golang.org/grpc/internal/backoff
google.golang.org/grpc/internal/balancerload
google.golang.org/grpc/internal/buffer
golang.org/x/sys/internal/unsafeheader
golang.org/x/sys/unix
google.golang.org/protobuf/internal/encoding/messageset
google.golang.org/protobuf/internal/strs
google.golang.org/protobuf/internal/encoding/text
google.golang.org/protobuf/internal/genid
google.golang.org/protobuf/internal/order
google.golang.org/protobuf/reflect/protoregistry
google.golang.org/protobuf/runtime/protoiface
google.golang.org/protobuf/proto
google.golang.org/protobuf/internal/encoding/defval
google.golang.org/protobuf/internal/descfmt
google.golang.org/protobuf/internal/descopts
google.golang.org/grpc/internal/envconfig
google.golang.org/protobuf/encoding/prototext
google.golang.org/protobuf/internal/filedesc
google.golang.org/grpc/internal/grpcsync
golang.org/x/text/transform
golang.org/x/text/unicode/bidi
golang.org/x/text/secure/bidirule
google.golang.org/protobuf/internal/encoding/tag
golang.org/x/text/unicode/norm
google.golang.org/protobuf/internal/impl
golang.org/x/net/idna
golang.org/x/net/http/httpguts
golang.org/x/net/http2/hpack
golang.org/x/net/http2
google.golang.org/protobuf/internal/filetype
google.golang.org/grpc/internal/syscall
google.golang.org/grpc/keepalive
google.golang.org/grpc/stats
google.golang.org/protobuf/runtime/protoimpl
google.golang.org/grpc/tap
golang.org/x/net/context/ctxhttp
golang.org/x/oauth2/internal
google.golang.org/protobuf/types/descriptorpb
google.golang.org/protobuf/types/known/anypb
github.com/golang/protobuf/ptypes/any
google.golang.org/protobuf/types/known/durationpb
github.com/golang/protobuf/ptypes/duration
google.golang.org/protobuf/types/known/timestamppb
google.golang.org/protobuf/reflect/protodesc
github.com/golang/protobuf/ptypes/timestamp
golang.org/x/oauth2
cloud.google.com/go/compute/metadata
golang.org/x/oauth2/google/internal/externalaccount
github.com/golang/protobuf/proto
golang.org/x/oauth2/jws
golang.org/x/oauth2/jwt
golang.org/x/oauth2/google
google.golang.org/api/internal/impersonate
github.com/golang/groupcache/lru
go.opencensus.io
go.opencensus.io/internal
go.opencensus.io/trace/internal
go.opencensus.io/trace/tracestate
google.golang.org/grpc/credentials
google.golang.org/grpc/encoding/proto
github.com/golang/protobuf/ptypes
google.golang.org/grpc/resolver
google.golang.org/grpc/balancer
google.golang.org/grpc/binarylog/grpc_binarylog_v1
google.golang.org/grpc/balancer/base
google.golang.org/grpc/balancer/roundrobin
google.golang.org/grpc/internal/grpcutil
google.golang.org/genproto/googleapis/rpc/status
google.golang.org/grpc/internal/channelz
google.golang.org/grpc/internal/status
google.golang.org/grpc/status
google.golang.org/grpc/internal/binarylog
google.golang.org/grpc/internal/serviceconfig
google.golang.org/grpc/internal/resolver
google.golang.org/grpc/balancer/grpclb/state
google.golang.org/grpc/internal/resolver/dns
google.golang.org/grpc/internal/resolver/passthrough
google.golang.org/grpc/internal/transport/networktype
google.golang.org/grpc/internal/resolver/unix
google.golang.org/grpc/internal/metadata
google.golang.org/grpc/peer
go.opencensus.io/trace
google.golang.org/grpc/internal/transport
go.opencensus.io/trace/propagation
go.opencensus.io/plugin/ochttp/propagation/b3
go.opencensus.io/resource
go.opencensus.io/metric/metricdata
go.opencensus.io/tag
go.opencensus.io/stats/internal
go.opencensus.io/stats
go.opencensus.io/internal/tagencoding
go.opencensus.io/metric/metricproducer
go.opencensus.io/stats/view
google.golang.org/grpc
go.opencensus.io/plugin/ochttp
google.golang.org/api/transport/cert
google.golang.org/api/transport/http/internal/propagation
github.com/rickb777/plural
github.com/rickb777/date/period
github.com/hi20160616/youtube_web/internal/pkg/render
golang.org/x/sync/errgroup
github.com/googleapis/gax-go/v2
google.golang.org/api/internal
google.golang.org/api/internal/gensupport
google.golang.org/api/option
google.golang.org/api/option/internaloption
google.golang.org/api/transport/internal/dca
google.golang.org/api/transport/http
google.golang.org/api/youtube/v3
github.com/hi20160616/youtube_web/internal/pkg/db/json
# github.com/hi20160616/youtube_web/internal/pkg/db/json
internal/pkg/db/json/activities.go:112:7: undefined: "github.com/pkg/errors".Is
internal/pkg/db/json/activities.go:147:12: undefined: os.ReadFile
internal/pkg/db/json/activities.go:149:6: undefined: "github.com/pkg/errors".Is
internal/pkg/db/json/channels.go:91:12: undefined: os.ReadFile
internal/pkg/db/json/channels.go:93:6: undefined: "github.com/pkg/errors".Is
note: module requires Go 1.16
 !     Push rejected, failed to compile Go app.
 !     Push failed
Build finished
Blogs
Careers
Documentation

after failed i try to set GOVERSION to 1.6 for failed package requirement bypass , but heroku not support go versions below 1.11 , see in action below :

-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/go
-----> Go app detected
-----> Fetching jq... done
-----> Fetching stdlib.sh.v8... done
-----> 
       Detected go modules via go.mod
-----> 
       Detected Module Name: github.com/hi20160616/youtube_web
-----> 
 !!    Using $GOVERSION override.
 !!         $GOVERSION = go1.6
 !!    
 !!    If this isn't what you want please run:'
 !!      heroku config:unset GOVERSION -a <app>
 !!    
 !!    You are using go1.6, which does not support Go modules
 !!    
 !!    Go modules are supported by go1.11 and above.
 !!    
 !!    Please add/update the comment in your go.mod file to specify a Go version >= go1.11 like so:
 !!    // +heroku goVersion go1.12.17
 !!    
 !!    Then commit and push again.
 !     Push rejected, failed to compile Go app.
 !     Push failed

overall please update go version of project & if it's possible make deploy to heroku button for easy deploy & fix other issues.
waiting for your response
finest regards

**Comment by hi20160616** [comment]
hi, there is elegant use on error judgment: use `os.ReadFile` will be easy to catch error of `ErrNotExist`, it will helpful to update or create database files auto, but it is new feature of go 1.16, so you should update your deploy env to go 1.16 at least.
